version: '3.8'
services:
  nginx:
    build: requirements/nginx/.
    image: nginx
    container_name: nginx
    env_file: ../.env
    ports:
      - "80:80"
    restart: on-failure
    #add depend on command here to depende on wordpress
  
  # wordpress:
  #   build: requirements/nginx/.
  #   container_name: wordpress
