version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
      - redis
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: /home/${USER}/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge