version: '3.8'
services:
  nginx:
    build: requirements/nginx/.
    image: nginx
    container_name: nginx
    env_file: .env
    ports:
      - "80:80"
    depends_on: wordpress
    restart: on-failure
    networks:
      - inception

  # wordpress:
  #   build: requirements/nginx/.
  #   container_name: wordpress


secrets:

volumes:

networks:
  inception:
    driver: bridge
