services:
  nginx:
    image: nginx:tar
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure

  mariadb:
    image: mariadb:tar
    container_name: mariadb
    build: ./requirements/mariadb
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    image: wordpress:tar
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - redis
      - mariadb
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html

  redis:
    image: redis:tar
    container_name: redis
    build: ./requirements/bonus/redis
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env
  ftp:
    image: ftp:tar
    container_name: ftp
    build: ./requirements/bonus/ftp
    ports:
      - "21:21"
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: on-failure
  
  adminer:
    image: adminer:tar
    container_name: adminer
    build: ./requirements/bonus/adminer
    depends_on:
      - mariadb
    ports:
      - "5000:5000"
    networks:
      - inception
    restart: on-failure
  
  static:
    image: static:tar
    container_name: static
    build: ./requirements/bonus/static
    depends_on:
      - nginx
      - wordpress
      - mariadb
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - inception
    restart: on-failure

  portainer:
    image: portainer:tar
    container_name: portainer
    build: ./requirements/bonus/portainer
    ports:
      - "9000:9000"
    networks:
      - inception
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: /home/ozahdi/data/wordpress
  
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: /home/ozahdi/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge